-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 11:07:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medikids_ex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medikids_ex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medikids_ex` DEFAULT CHARACTER SET utf8 ;
USE `medikids_ex` ;

-- -----------------------------------------------------
-- Table `medikids_ex`.`Specialties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Specialties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Doctors``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Doctors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_Names` VARCHAR(45) NOT NULL,
  `Last_Names` VARCHAR(45) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Profile_Photo` VARCHAR(100) NOT NULL,
  `Speciality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Speciality_id_idx` (`Speciality_id` ASC) VISIBLE,
  CONSTRAINT `Speciality_id`
    FOREIGN KEY (`Speciality_id`)
    REFERENCES `medikids_ex`.`Specialties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Responsible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Responsible` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_Names` VARCHAR(45) NOT NULL,
  `Last_Names` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `DUI` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Profile_Photo` VARCHAR(100) NOT NULL,
  `Reset_Pass_Token` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Event_Name` VARCHAR(45) NOT NULL,
  `Event_Date` DATE NOT NULL,
  `Start_Time` TIME NOT NULL,
  `End_Time` TIME NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `Responsible_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Responsible_id_idx` (`Responsible_id` ASC) VISIBLE,
  CONSTRAINT `Responsible_id`
    FOREIGN KEY (`Responsible_id`)
    REFERENCES `medikids_ex`.`Responsible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_Names` VARCHAR(45) NOT NULL,
  `Last_Names` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Blood_Type` VARCHAR(45) NOT NULL,
  `Weight` FLOAT NOT NULL,
  `Height` FLOAT NOT NULL,
  `Responsible_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Responsible_id_idx` (`Responsible_id` ASC) VISIBLE,
  CONSTRAINT `Responsible_id`
    FOREIGN KEY (`Responsible_id`)
    REFERENCES `medikids_ex`.`Responsible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Medical_Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Medical_Prescription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Patient_id` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Patient_id_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `Patient_id0`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `medikids_ex`.`Patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Medical_Recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Medical_Recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Starting_Date` DATE NOT NULL,
  `Finishing_Date` DATE NOT NULL,
  `Dose` VARCHAR(45) NOT NULL,
  `Medical_Prescription_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Medical_Prescription_id_idx` (`Medical_Prescription_id` ASC) VISIBLE,
  CONSTRAINT `Medical_Prescription_id`
    FOREIGN KEY (`Medical_Prescription_id`)
    REFERENCES `medikids_ex`.`Medical_Prescription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Medical_Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Medical_Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Doctor_id` INT NOT NULL,
  `Responsible_id` INT NOT NULL,
  `Patient_id` INT NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `Date` DATETIME NOT NULL,
  `Hour` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Responsible_Appointment_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Responsible_Appointment_Detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Responsible_id` INT NOT NULL,
  `Appointment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Responsible_id_idx` (`Responsible_id` ASC) VISIBLE,
  INDEX `Appointment_id_idx` (`Appointment_id` ASC) VISIBLE,
  CONSTRAINT `Responsible_id`
    FOREIGN KEY (`Responsible_id`)
    REFERENCES `medikids_ex`.`Responsible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Appointment_id`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `medikids_ex`.`Medical_Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Doctor_Appointment_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Doctor_Appointment_Detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Doctor_id` INT NOT NULL,
  `Appointment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Doctor_id_idx` (`Doctor_id` ASC) VISIBLE,
  INDEX `Appointment_id_idx` (`Appointment_id` ASC) VISIBLE,
  CONSTRAINT `Doctor_id`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `medikids_ex`.`Doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Appointment_id`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `medikids_ex`.`Medical_Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Medical_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Medical_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Patient_id` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Diagnosis` LONGTEXT NOT NULL,
  `Weight` FLOAT NOT NULL,
  `Temperature` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Patient_id_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `Patient_id`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `medikids_ex`.`Patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medikids_ex`.`Notices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medikids_ex`.`Notices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Description` LONGTEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Doctor_id_idx` (`Doctor_id` ASC) VISIBLE,
  CONSTRAINT `Doctor_id`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `medikids_ex`.`Doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
