export { IndexPage } from "./IndexPage.jsx";
export { Error404 } from "./Error404.jsx";
export { MainAgenda } from "./MainAgenda.jsx";
export { Inbox } from "./Inbox.jsx";
export { ActivePatients } from "./Patients/ActivePatients.jsx";
export { MedicalRecords } from "./Patients/MedicalRecords.jsx";
export { PatientsDetails } from "./Patients/PatientsDetails.jsx";
export { MedicalAppoinment } from "./Patients/AttendMedicalAppoinment.jsx"
export { LoginPage } from "./auth/LoginPage.jsx"
